"""
Configuration parameters for Iris Recognition.
"""

# Image Normalization
NORM_HEIGHT = 64
NORM_WIDTH = 512

# Preprocessing / Detection
PUPIL_MIN_AREA = 50
PUPIL_THRESH_START = 10
PUPIL_THRESH_END = 80
PUPIL_THRESH_STEP = 5
HOUGH_DP = 1.0
HOUGH_MIN_DIST =  100
HOUGH_PARAM1 = 50
HOUGH_PARAM2 = 15
HOUGH_MIN_RADIUS = 10
HOUGH_MAX_RADIUS = 50

# Gabor Filter Parameters
GABOR_KSIZE = 31
GABOR_SIGMA = 3.0
GABOR_THETA = 0
GABOR_LAMBD = 8.0
GABOR_GAMMA = 0.5

# Matching
SHIFT_RANGE = 12